# broot config file. Place in ~/.config/broot/ 
# https://github.com/Canop/broot

[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "/usr/bin/vim {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

